export const interiors = [
    {id:1, name: "dashboard"},
    {id:2, name: "dashboard"},
    {id:3, name: "dashboard"},
    {id:4, name: "dashboard"},
    {id:5, name: "dashboard"},
    {id:6, name: "dashboard"},
    {id:7, name: "dashboard"},
    {id:9, name: "dashboard"},
    {id:10, name: "dashboard"},
    {id:11, name: "dashboard"},
    {id:12, name: "dashboard"},
    {id:13, name: "dashboard"},
    {id:14, name: "dashboard"},
    {id:15, name: "dashboard"},
    {id:16, name: "dashboard"},
    {id:18, name: "dashboard"},
    {id:19, name: "dashboard"},
    {id:20, name: "dashboard"},
]