const items =[
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},
{title: " hello", tag:["mix"],img: "card2.png"},



];


